centos5-devtoolset2-gcc4: Fix use of "sudo" removing version provided by devtoolset-2
Since gosu is installed along with an existing wrapper (see [2]), this
didn't work well with script provided by devtoolset-2 (see [1]), the
following error was reported:

  error: exec: "-E": executable file not found in $PATH

For future reference, the content of the removed scripts:

[1] File: /opt/rh/devtoolset-2/root/usr/bin/sudo

8<---8<---8<---8<---8<---8<---8<---8<---
#! /bin/sh
# TODO: parse & pass-through sudo options from $@
sudo_options="-E"

for arg in "$@"
do
   case "$arg" in
    *\'*)
      arg=`echo "$arg" | sed "s/'/'\\\\\\\\''/g"` ;;
   esac
   cmd_options="$cmd_options '$arg'"
done

exec /usr/bin/sudo $sudo_options LD_LIBRARY_PATH=$LD_LIBRARY_PATH PATH=$PATH scl enable devtoolset-2 "$cmd_options"
8<---8<---8<---8<---8<---8<---8<---8<---

and the content of our wrapper:

[2] File: /usr/bin/sudo

8<---8<---8<---8<---8<---8<---8<---8<---
#!/bin/sh

# Emulate the sudo command

exec gosu root:root "$@"
8<---8<---8<---8<---8<---8<---8<---8<---